version: '3.8'

services:
  lambdapi:
    build: .
    volumes:
      - .:/app
      - ./functions.db:/app/functions.db
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/lambdapi/files:/tmp/lambdapi/files
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    container_name: redis
    expose:
      - 6379
